spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./src/test/h2db/test:testdb;MODE=MySQL
    username: sa
    password:
    initialization-mode: always
  h2.console.enabled: true
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

# actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"